### ISSUE TITLE
Sync service must be restarted after adding a namespace

### ISSUE THREAD

**Issue by dkleissa** [gigantum/hybrid-object-store#243]
# Description
Currently, the sync service must be restarted after you add a namespace or you must wait until the STS credentials inside the sync service `PopulatedMetaConfiguration`s automatically renew. This is because the policy associated with the credentials does not have access to the bucket that is created at test time.

Integration tests have been renamed to run after sync tests, which reload the configurations and update the policy.

We could add a signal so the `PopulatedMetaConfiguration`s automatically reload when a namespace is added, but that seems overly complex given future improvements. This likely can and should be addressed in https://github.com/gigantum/hybrid-object-store/issues/234 when sync and meta processing is merged into policy based operations.

For now, a callout should be made in the admin docs on how to restart the sync service after a namespace is added (https://github.com/gigantum/hybrid-object-store/issues/198)

**Comment by derek-pryor** [comment]
I don't think we can get a way from adding a new API Sync Message for a new namespace (and possibly deleting a namespace). If we had the ability to push notifications from the core service to the sync service we could use another approach. (But we went with polling)

**Comment by derek-pryor** [comment]
Since there is not currently a way to update the list of `PopulatedMetaConfigurations` (right now you just reload all of the `PopulatedMetaConfigurations`) I think it would be best to tackle this after merging and making a common configuration structure. Keeping this requirement in mind and with the need a the `PopulatedSyncConfigurations` to do a delta style update of running resources I think that we can easily accommodate this requirement with minimal extra work.
